name: pg-emg3d
channels:
    - conda-forge
    - defaults
    - gimli
dependencies:
    - python
    - pygimli>=1.4
    - jupyter
    - ipywidgets
    - ipykernel
    - empymod
    - discretize
    - xarray
    - matplotlib
    - h5py
    - tqdm
    - scooby
    - pip
    - pip:
      - git+https://github.com/emsig/emg3d@inversion
