name: pg-emg3d
channels:
    - gimli
    - conda-forge
dependencies:
    - python
    - pgcore
    - jupyter
    - ipywidgets
    - ipykernel
    - empymod
    - discretize
    - xarray
    - matplotlib
    - h5py
    - tqdm
    - scooby
    - pip
    - pip:
      - git+https://github.com/emsig/emg3d@inversion
      - git+https://github.com/gimli-org/gimli@dev
